name: Build and push docker image
on:
  workflow_dispatch:
  release:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Downcase repo
        run: echo "REPO_LOWER=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: '${{ github.repository }}'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Github Container Login
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          target: build
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/mapnik-python-aws:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/mapnik-python-aws:latest
